-- MySQL Script generated by MySQL Workbench
-- Thu Nov  9 15:40:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema locadora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema locadora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `locadora` DEFAULT CHARACTER SET utf8 ;
USE `locadora` ;

-- -----------------------------------------------------
-- Table `locadora`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`funcionario` (
  `idFuncionario` INT NOT NULL UNIQUE,
  `salario` VARCHAR(45) NOT NULL,
  `isGerente` VARCHAR(45) BINARY NOT NULL,
  `locadora_idLcadora` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  CONSTRAINT `fk_funcionario_locadora1`
    FOREIGN KEY (`locadora_idLcadora`)
    REFERENCES `locadora`.`locadora` (`idLcadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`locadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`locadora` (
  `idLcadora` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `gerente` INT NOT NULL,
  PRIMARY KEY (`idLcadora`),
  CONSTRAINT `fk_locadora_funcionario1`
    FOREIGN KEY (`gerente`)
    REFERENCES `locadora`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`filme` (
  `idfilme` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `lancamento` DATE NOT NULL,
  PRIMARY KEY (`idfilme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`genero` (
  `idGenero` INT NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`filme_has_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`filme_has_genero` (
  `filme_idfilme` INT NOT NULL,
  `genero_idGenero` INT NOT NULL,
  PRIMARY KEY (`filme_idfilme`, `genero_idGenero`),
  CONSTRAINT `fk_filme_has_genero_filme1`
    FOREIGN KEY (`filme_idfilme`)
    REFERENCES `locadora`.`filme` (`idfilme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filme_has_genero_genero1`
    FOREIGN KEY (`genero_idGenero`)
    REFERENCES `locadora`.`genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`cliente` (
  `idCliente` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(13) NOT NULL,
  `endereco` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `locadora_idLcadora` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  CONSTRAINT `fk_cliente_locadora1`
    FOREIGN KEY (`locadora_idLcadora`)
    REFERENCES `locadora`.`locadora` (`idLcadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`aluguel` (
  `idAlguel` INT NOT NULL,
  `preco_total` INT NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idAlguel`),
  CONSTRAINT `fk_alguel_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `locadora`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`pagamento` (
  `idPagamento` INT NOT NULL,
  `alguel_idAlguel` INT NOT NULL,
  `forma` ENUM('cartao', 'dinheiro', 'pix') NOT NULL,
  `data` DATE NOT NULL,
  `pago` TINYINT NOT NULL,
  PRIMARY KEY (`idPagamento`, `alguel_idAlguel`),
  CONSTRAINT `fk_pagamento_alguel1`
    FOREIGN KEY (`alguel_idAlguel`)
    REFERENCES `locadora`.`aluguel` (`idAlguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`filmes_alugados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`filmes_alugados` (
  `alguel_idAlguel` INT NOT NULL,
  `filme_idfilme` INT NOT NULL,
  PRIMARY KEY (`alguel_idAlguel`, `filme_idfilme`),
  CONSTRAINT `fk_alguel_has_filme_alguel1`
    FOREIGN KEY (`alguel_idAlguel`)
    REFERENCES `locadora`.`aluguel` (`idAlguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alguel_has_filme_filme1`
    FOREIGN KEY (`filme_idfilme`)
    REFERENCES `locadora`.`filme` (`idfilme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`locadora_has_filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`locadora_has_filme` (
  `locadora_idLcadora` INT NOT NULL,
  `filme_idfilme` INT NOT NULL,
  `copias` INT NOT NULL,
  `disponiveis` TINYINT NOT NULL,
  PRIMARY KEY (`locadora_idLcadora`, `filme_idfilme`),
  CONSTRAINT `fk_locadora_has_filme_locadora1`
    FOREIGN KEY (`locadora_idLcadora`)
    REFERENCES `locadora`.`locadora` (`idLcadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locadora_has_filme_filme1`
    FOREIGN KEY (`filme_idfilme`)
    REFERENCES `locadora`.`filme` (`idfilme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
