-- MySQL Script generated by MySQL Workbench
-- Fri Nov 10 14:19:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema locadora_bd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `locadora_bd` ;

-- -----------------------------------------------------
-- Schema locadora_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `locadora_bd` DEFAULT CHARACTER SET utf8 ;
USE `locadora_bd` ;

-- -----------------------------------------------------
-- Table `locadora_bd`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora_bd`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `salario` INT NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `id_locadora` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_funcionario_locadora_idx` (`id_locadora` ASC) INVISIBLE,
  CONSTRAINT `fk_funcionario_locadora`
    FOREIGN KEY (`id_locadora`)
    REFERENCES `locadora_bd`.`locadora` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora_bd`.`gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora_bd`.`gerente` (
  `id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  UNIQUE INDEX `id_funcionario_UNIQUE` (`id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_gerente_funcionario`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `locadora_bd`.`funcionario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora_bd`.`locadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora_bd`.`locadora` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `id_gerente` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_locadora_gerente_idx` (`id_gerente` ASC) INVISIBLE,
  CONSTRAINT `fk_locadora_gerente`
    FOREIGN KEY (`id_gerente`)
    REFERENCES `locadora_bd`.`gerente` (`id_funcionario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora_bd`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora_bd`.`filme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `lancamento` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora_bd`.`generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora_bd`.`generos` (
  `id_filme` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_filme`),
  INDEX `fk_generos_filme_idx` (`id_filme` ASC) VISIBLE,
  CONSTRAINT `fk_generos_filme`
    FOREIGN KEY (`id_filme`)
    REFERENCES `locadora_bd`.`filme` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora_bd`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora_bd`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(13) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(100) NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora_bd`.`aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora_bd`.`aluguel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preco_total` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_locadora` INT NOT NULL,
  PRIMARY KEY (`id`, `id_cliente`, `id_locadora`),
  INDEX `fk_alguel_cliente_idx` (`id_cliente` ASC) INVISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_aluguel_locadora_idx` (`id_locadora` ASC) VISIBLE,
  CONSTRAINT `fk_alguel_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `locadora_bd`.`cliente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_aluguel_locadora`
    FOREIGN KEY (`id_locadora`)
    REFERENCES `locadora_bd`.`locadora` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora_bd`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora_bd`.`pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_aluguel` INT NOT NULL,
  `forma` ENUM('cartao', 'dinheiro', 'pix') NOT NULL,
  `data` DATE NOT NULL,
  `pago` TINYINT NOT NULL,
  PRIMARY KEY (`id`, `id_aluguel`),
  INDEX `fk_pagamento_alguel_idx` (`id_aluguel` ASC) INVISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) INVISIBLE,
  CONSTRAINT `fk_pagamento_alguel`
    FOREIGN KEY (`id_aluguel`)
    REFERENCES `locadora_bd`.`aluguel` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora_bd`.`locadora_filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora_bd`.`locadora_filme` (
  `id_locadora` INT NOT NULL,
  `id_filme` INT NOT NULL,
  `n_copias` INT NOT NULL,
  `qtd_disponiveis` INT NOT NULL,
  PRIMARY KEY (`id_locadora`, `id_filme`),
  INDEX `fk_locadora_filme_filme_idx` (`id_filme` ASC) INVISIBLE,
  INDEX `fk_locadora_filme_locadora_idx` (`id_locadora` ASC) VISIBLE,
  CONSTRAINT `fk_locadora_filme_locadora`
    FOREIGN KEY (`id_locadora`)
    REFERENCES `locadora_bd`.`locadora` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_locadora_filme_filme`
    FOREIGN KEY (`id_filme`)
    REFERENCES `locadora_bd`.`filme` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora_bd`.`filme_alugado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora_bd`.`filme_alugado` (
  `id_aluguel` INT NOT NULL,
  `id_filme` INT NOT NULL,
  PRIMARY KEY (`id_aluguel`, `id_filme`),
  INDEX `fk_filme_alugado_filme_idx` (`id_filme` ASC) VISIBLE,
  INDEX `fk_filme_alugado_aluguel_idx` (`id_aluguel` ASC) INVISIBLE,
  CONSTRAINT `fk_filme_alugado_aluguel`
    FOREIGN KEY (`id_aluguel`)
    REFERENCES `locadora_bd`.`aluguel` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_filme_alugado_filme`
    FOREIGN KEY (`id_filme`)
    REFERENCES `locadora_bd`.`filme` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
